export const users= [
  {
    id: 1,
    name: 'Ivan1',
    position:'manager',
    department:'qwerty_dep',
    company:'qwerty_company',
    avatar:'',
  },
  {
    id: 2,
    name: 'Ivan2',
    position:'manager',
    department:'qwerty_dep',
    company:'qwerty_company',
    avatar:'',
  },
  {
    id: 3,
    name: 'Ivan3',
    position:'manager',
    department:'qwerty_dep',
    company:'qwerty_company',
    avatar:'',
  },
  {
    id: 4,
    name: 'Ivan4',
    position:'manager',
    department:'qwerty_dep',
    company:'qwerty_company',
    avatar:'',
  },
  {
    id: 5,
    name: 'Ivan5',
    position:'manager',
    department:'qwerty_dep',
    company:'qwerty_company',
    avatar:'',
  },
];
